# Generated by Django 5.2 on 2025-05-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('vacation', 'Ежегодный оплачиваемый отпуск'), ('sick', 'Больничный лист'), ('study', 'Учебный отпуск'), ('business', 'Командировка'), ('unpaid', 'Отпуск без сохранения заработной платы'), ('maternity', 'Декретный отпуск'), ('childcare', 'Отпуск по уходу за ребёнком'), ('other', 'Прочий отпуск')], max_length=20),
        ),
    ]
