# Generated by Django 5.2 on 2025-05-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shift_type',
            field=models.CharField(choices=[('5_2', 'Пятидневка (5/2)'), ('2_2', 'Сменный график (2/2)'), ('1_3', 'Один через три (1/3)'), ('custom', 'Произвольный график')], default='5_2', max_length=10),
        ),
    ]
