# Generated by Django 5.2 on 2025-05-19 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_gender_customuser_shift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shift_start_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 1, 1), null=True),
        ),
    ]
