# Generated by Django 5.2 on 2025-05-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customuser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, choices=[('master', 'Мастер по обслуживанию абонентов'), ('specialist', 'Универсальный специалист связи'), ('engineer', 'Инженер'), ('service_engineer', 'Сервисный инженер'), ('support', 'Специалист по сопровождению'), ('lead_engineer', 'Ведущий Инженер'), ('chief', 'Начальник участка')], max_length=100, verbose_name='Должность'),
        ),
    ]
