# Generated by Django 5.2.1 on 2025-05-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customuser_telegram_id_telegramlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlink',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramlink',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
