# Generated by Django 5.2.1 on 2025-06-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_telegramlink_telegram_id_alter_telegramlink_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='ID пользователя в Telegram для связи с ботом', null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.DeleteModel(
            name='TelegramLink',
        ),
    ]
