# Generated by Django 5.2.1 on 2025-06-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_telegramlinkcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlinkcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
