# Generated by Django 5.2.1 on 2025-06-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customuser_address_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contract_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип трудового договора'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager',
            field=models.CharField(blank=True, max_length=100, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Семейное положение'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Личный email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Рабочий email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Рабочий телефон'),
        ),
    ]
