# Generated by Django 5.2.1 on 2025-06-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_customuser_address_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на отпуск', 'verbose_name_plural': 'Заявки на отпуск'},
        ),
        migrations.AlterModelOptions(
            name='telegramlinkcode',
            options={'verbose_name': 'Код привязки Telegram', 'verbose_name_plural': 'Коды привязки Telegram'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Табельный номер'),
        ),
    ]
